name: Terraform

on:
    push:
        branches:
        - main

jobs:
  plan:
    name: Format Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      
      - name: Setup
        uses: hashicorp/setup-terraform@v1
      
      - name: Format
        run: terraform fmt -check -diff -recursive .

      - name: Initialize
        run: |
          terraform init
      
      - name: Validate
        run: |
          terraform validate